In [1]:
#20MAI0024
#ADITYA SHELKE

import numpy as np

In [2]:

values = ([2,3],[5,6],[8,9])
print("Training input values without Bias\n", values)


Training input values without Bias
 ([2, 3], [5, 6], [8, 9])


In [3]:
#Adding Bias to the input values
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training input values with bias in it\n",values)


Training input values with bias in it
 [[-1  2  3]
 [-1  5  6]
 [-1  8  9]]


In [4]:
#Creating random weights
m=3     #number of elements in each row of inputs
n=1 
weights = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",weights)


Initial random weights
 [[-0.46289061]
 [-0.41591814]
 [-0.4899877 ]]


In [5]:

#Target values Matrix
final = ([0],[1],[1])
print("Training data target values are\n", final)


Training data target values are
 ([0], [1], [1])


In [6]:
#Method for updating weights
def updateWeights(weights, inputs, activation, targets):
    eta = 0.25
    weights += eta*np.dot(np.transpose(inputs), targets - activation)
    return weights


In [7]:
#Creating Methods for Learning
def  prediction (inputs, weights, targets):
    #representing Activation function with 'ack [[]]' variable
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(weights)):
            ack[i] += inputs[i][j] * weights[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        #checking values with target
        if(targets[i] != ack[i]):
            weights = updateWeights(weights, inputs, ack[i], targets)
        print(ack[i])
    return weights


In [8]:
#Training our model and extracting stable weights
iterations = 5
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    weights = prediction(values, weights, final)
    
print("\nTrained Weights\n", weights)



Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Iteration  5 

[1]
[1]
[1]

Trained Weights
 [[0.03710939]
 [0.83408186]
 [0.2600123 ]]


In [9]:
#Testing our own data
def perceptronPredict(weights, newInput):
    ac = np.dot(newInput, weights)
    ac = np.where(ac>0, 1, 0)
    print(ac)


newInput = ([-1.0, 7, 8])
perceptronPredict(weights, newInput)

[1]


In [13]:

from IPython.core.display import display, HTML
display(HTML("""<a href="https://github.com/adityashelke5/Deep-Learning.git">Github_Link</a>"""))